// A list of all actions in the system.
import { createTypes } from 'reduxsauce';

export default createTypes(`
  LOGIN_ATTEMPT
  LOGIN_SUCCESS
  LOGIN_FAILURE
  
  GETBUILD_ATTEMPT
  GETBUILD_SUCCESS
  GETBUILD_FAILURE
  GETBUILD_INIT
  
  GETBUILDS_ATTEMPT
  GETBUILDS_SUCCESS
  GETBUILDS_FAILURE
  GETBUILDS_INIT
  
  GETJOBS_ATTEMPT
  GETJOBS_SUCCESS
  GETJOBS_FAILURE
  GETJOBS_INIT

  LOGOUT_ATTEMPT
  LOGOUT_SUCCESS
  LOGOUT_FAILURE

  STARTUP
`);
